Repository nyxx-discord/nyxx, pull requests merged in 2020-05, with the labels that each got.

#65 Alternative command framework - Commander
  nyxx.commander/analysis_options.yaml
  nyxx.commander/lib/commander.dart
  nyxx.commander/lib/src/CommandContext.dart
  nyxx.commander/lib/src/CommandHandler.dart
  nyxx.commander/lib/src/Commander.dart
  nyxx.commander/lib/src/utils.dart
  nyxx.commander/pubspec.yaml
  nyxx.commander/test/commander-test.dart
  nyxx.commands/lib/commands.dart
  nyxx.commands/lib/src/Annotations.dart
  nyxx.commands/lib/src/CommandsFramework.dart
  nyxx.commands/lib/src/CommandsParser.dart
  nyxx.commands/lib/src/CooldownCache.dart
  nyxx.commands/lib/src/Helpers.dart
  nyxx.commands/lib/src/Processors.dart
  nyxx.commands/lib/src/TypeConverter.dart
  nyxx.commands/lib/src/_CommandsMetadata.dart
  nyxx.commands/lib/src/utils/utils.dart
Labels: enhancement

#69 Fixing setPresence method
  nyxx/lib/src/Shard.dart
  nyxx/lib/src/core/user/Presence.dart
Labels: bug, enhancement

#71 Fix DMChannel recognition/creation
  nyxx/lib/src/core/channel/dm/DMChannel.dart
Labels: bug

#77 Adding ActivityType documentation & fixing "custom" ActivityType value
  nyxx/lib/src/core/user/Presence.dart
Labels: enhancement
