Repository nyxx-discord/nyxx, pull requests merged in 2021-07, with the labels that each got.

#132 [feature] Implementation of dropdowns/selection menus
  nyxx/lib/src/core/message/components/MessageComponent.dart
  nyxx_interactions/lib/src/Interactions.dart
  nyxx_interactions/lib/src/builders/ArgChoiceBuilder.dart
  nyxx_interactions/lib/src/builders/CommandOptionBuilder.dart
  nyxx_interactions/lib/src/builders/ComponentBuilder.dart
  nyxx_interactions/lib/src/events/InteractionEvent.dart
  nyxx_interactions/lib/src/internal/_EventController.dart
  nyxx_interactions/lib/src/models/Interaction.dart
Labels: enhancement, in-progress

#142 [feature] New threads features
  nyxx/lib/src/core/guild/GuildFeature.dart
  nyxx/lib/src/utils/builders/ThreadBuilder.dart
Labels: enhancement

#145 Redesign of channel edit logic
  nyxx/example/channel.dart
  nyxx/lib/src/core/channel/guild/GuildChannel.dart
  nyxx/lib/src/core/channel/guild/TextGuildChannel.dart
  nyxx/lib/src/core/channel/guild/VoiceChannel.dart
  nyxx/lib/src/internal/_HttpEndpoints.dart
  nyxx/lib/src/utils/builders/GuildBuilder.dart
Labels: bug, enhancement, in-progress

#147 Interactions Fixes
  nyxx/lib/src/internal/http/HttpHandler.dart
  nyxx_interactions/lib/src/Interactions.dart
  nyxx_interactions/lib/src/builders/SlashCommandBuilder.dart
  nyxx_interactions/pubspec.yaml
Labels: bug

#144 First implementation of stickers
  nyxx/lib/nyxx.dart
  nyxx/lib/src/Nyxx.dart
  nyxx/lib/src/core/guild/Guild.dart
  nyxx/lib/src/core/message/Message.dart
  nyxx/lib/src/core/message/Sticker.dart
  nyxx/lib/src/core/permissions/PermissionsConstants.dart
  nyxx/lib/src/events/GuildEvents.dart
  nyxx/lib/src/internal/_EventController.dart
  nyxx/lib/src/internal/_HttpEndpoints.dart
  nyxx/lib/src/internal/http/HttpRequest.dart
  nyxx/lib/src/utils/builders/StickerBuilder.dart
Labels: bug, enhancement, in-progress

#149 [feature] Webhook overhaul
  nyxx/lib/src/core/guild/Webhook.dart
  nyxx/lib/src/internal/_HttpEndpoints.dart
  nyxx/pubspec.yaml
  nyxx_commander/pubspec.yaml
  nyxx_extensions/pubspec.yaml
  nyxx_interactions/pubspec.yaml
  nyxx_lavalink/pubspec.yaml
Labels: bug, enhancement, in-progress

#141 [feature] Member avatars
  nyxx/lib/src/core/guild/Guild.dart
  nyxx/lib/src/core/user/Member.dart
  nyxx/lib/src/internal/_HttpEndpoints.dart
Labels: enhancement, in-progress

#150 [feature] Rework of presence related code
  nyxx/lib/src/core/user/Presence.dart
  nyxx/lib/src/utils/builders/PresenceBuilder.dart
  nyxx_interactions/lib/src/Interactions.dart
Labels: bug, enhancement, in-progress

#151 [feature/fix] Docs rework
  nyxx/example/channel.dart
  nyxx/example/create-add-role.dart
  nyxx/example/embeds.dart
  nyxx/example/example.dart
  nyxx/example/invite.dart
  nyxx/example/kick-ban.dart
  nyxx/example/permissions.dart
  nyxx/example/ping-pong.dart
  nyxx/example/reply-to-message.dart
  nyxx/example/sending-file.dart
  nyxx/lib/src/core/guild/Webhook.dart
  nyxx/lib/src/internal/_HttpEndpoints.dart
  nyxx/lib/src/utils/builders/ReplyBuilder.dart
  nyxx_extensions/example/example.dart
  nyxx_extensions/lib/scheduled_event.dart
  nyxx_extensions/lib/src/emoji/EmojiUtils.dart
  nyxx_extensions/lib/src/scheduler/scheduler.dart
  nyxx_extensions/test/extensions-tests.dart
  nyxx_interactions/example/basic.dart
  nyxx_interactions/example/buttons-and-dropdowns.dart
  nyxx_lavalink/example/example.dart
Labels: bug, in-progress

#160 Migrate separate arguments with file format to AttachmentBuilder
  nyxx/lib/src/core/channel/guild/TextGuildChannel.dart
  nyxx/lib/src/core/guild/ClientUser.dart
  nyxx/lib/src/core/guild/Guild.dart
  nyxx/lib/src/core/guild/Webhook.dart
  nyxx/lib/src/internal/_HttpEndpoints.dart
  nyxx/lib/src/utils/builders/AttachmentBuilder.dart
  nyxx/lib/src/utils/builders/MessageBuilder.dart
  nyxx/lib/src/utils/utils.dart
  nyxx/test/unit.dart
Labels: enhancement
