Repository nyxx-discord/nyxx, pull requests merged in 2021-06, with the labels that each got.

#134 [feature] Ratelimits Imrovements
  nyxx/lib/src/internal/http/HttpBucket.dart
  nyxx/lib/src/internal/http/HttpHandler.dart
Labels: enhancement

#131 General Enhancements & Issues
  nyxx/lib/src/utils/builders/EmbedAuthorBuilder.dart
  nyxx/lib/src/utils/builders/EmbedBuilder.dart
  nyxx/lib/src/utils/builders/EmbedFooterBuilder.dart
  nyxx/lib/src/utils/builders/MessageBuilder.dart
  nyxx/test/travis.dart
  nyxx_extensions/lib/embedbuilder_extension.dart
  nyxx_extensions/lib/src/embedbuilder_extension.dart
  nyxx_extensions/test/extensions-tests.dart
Labels: bug, enhancement, in-progress

#137 [feature] Threads new featues / general improvements
  nyxx/lib/nyxx.dart
  nyxx/lib/src/Nyxx.dart
  nyxx/lib/src/core/Invite.dart
  nyxx/lib/src/core/channel/DMChannel.dart
  nyxx/lib/src/core/channel/ThreadChannel.dart
  nyxx/lib/src/core/channel/ThreadPreviewChannel.dart
  nyxx/lib/src/core/channel/guild/GuildChannel.dart
  nyxx/lib/src/core/channel/guild/TextGuildChannel.dart
  nyxx/lib/src/core/channel/guild/VoiceChannel.dart
  nyxx/lib/src/core/guild/ClientUser.dart
  nyxx/lib/src/core/guild/Guild.dart
  nyxx/lib/src/core/guild/Role.dart
  nyxx/lib/src/core/guild/Webhook.dart
  nyxx/lib/src/core/message/GuildEmoji.dart
  nyxx/lib/src/core/message/Message.dart
  nyxx/lib/src/core/permissions/Permissions.dart
  nyxx/lib/src/core/permissions/PermissionsConstants.dart
  nyxx/lib/src/core/user/Member.dart
  nyxx/lib/src/core/user/User.dart
  nyxx/lib/src/events/ThreadDeletedEvent.dart
  nyxx/lib/src/events/ThreadMembersUpdateEvent.dart
  nyxx/lib/src/internal/_HttpEndpoints.dart
  nyxx/lib/src/internal/cache/Cacheable.dart
  nyxx/lib/src/internal/response_wrapper/ThreadListResultWrapper.dart
  nyxx/lib/src/utils/builders/PermissionsBuilder.dart
Labels: bug, enhancement, in-progress

#139 Lavalink support
  nyxx_lavalink/.gitignore
  nyxx_lavalink/CHANGELOG.md
  nyxx_lavalink/LICENSE
  nyxx_lavalink/README.md
  nyxx_lavalink/analysis_options.yaml
  nyxx_lavalink/example/example.dart
  nyxx_lavalink/lib/lavalink.dart
  nyxx_lavalink/lib/src/Cluster.dart
  nyxx_lavalink/lib/src/ClusterException.dart
  nyxx_lavalink/lib/src/HttpException.dart
  nyxx_lavalink/lib/src/_EventDispatcher.dart
  nyxx_lavalink/lib/src/model/BaseEvent.dart
  nyxx_lavalink/lib/src/model/Exception.dart
  nyxx_lavalink/lib/src/model/GuildPlayer.dart
  nyxx_lavalink/lib/src/model/PlayParameters.dart
  nyxx_lavalink/lib/src/model/PlayerUpdate.dart
  nyxx_lavalink/lib/src/model/Stats.dart
  nyxx_lavalink/lib/src/model/Track.dart
  nyxx_lavalink/lib/src/model/TrackEnd.dart
  nyxx_lavalink/lib/src/model/TrackStart.dart
  nyxx_lavalink/lib/src/model/WebSocketClosed.dart
  nyxx_lavalink/lib/src/node/Node.dart
  nyxx_lavalink/lib/src/node/Options.dart
  nyxx_lavalink/lib/src/node/nodeRunner.dart
  nyxx_lavalink/pubspec.yaml
  nyxx_lavalink/test/nyxx_lavalink_test.dart
Labels: enhancement

#135 [feature] Trace logging
  nyxx/lib/src/ClientOptions.dart
  nyxx/lib/src/Nyxx.dart
  nyxx/lib/src/internal/_ConnectionManager.dart
  nyxx/lib/src/internal/http/HttpBucket.dart
  nyxx/lib/src/internal/shard/Shard.dart
  nyxx/lib/src/internal/shard/ShardManager.dart
  nyxx/lib/src/internal/shard/shardHandler.dart
  nyxx_commander/lib/src/Commander.dart
  nyxx_interactions/lib/src/Interactions.dart
  nyxx_interactions/lib/src/events/InteractionEvent.dart
Labels: enhancement, in-progress
