Repository nyxx-discord/nyxx, pull requests merged in 2021-08, with the labels that each got.

#167 GuildStickers from raw should have a nullable String type.
  nyxx/lib/src/core/message/Sticker.dart
Labels: bug

#158 Implement resolved field for slash command
  nyxx/lib/src/core/channel/guild/GuildChannel.dart
  nyxx/lib/src/core/message/Message.dart
  nyxx/lib/src/core/user/Member.dart
  nyxx_interactions/lib/interactions.dart
  nyxx_interactions/lib/src/models/Interaction.dart
  nyxx_interactions/lib/src/models/InteractionDataResolved.dart
Labels: enhancement, in-progress

#169 Refactor InteractionEvent to contain Interactions reference
  nyxx_interactions/lib/src/Interactions.dart
  nyxx_interactions/lib/src/events/InteractionEvent.dart
Labels: enhancement

#170 [feature] Context menus
  nyxx_interactions/lib/interactions.dart
  nyxx_interactions/lib/src/builders/SlashCommandBuilder.dart
  nyxx_interactions/lib/src/models/SlashCommandType.dart
Labels: enhancement

#171 Multiple search platforms support
  nyxx_lavalink/lib/lavalink.dart
  nyxx_lavalink/lib/src/model/SearchPlatform.dart
  nyxx_lavalink/lib/src/node/Node.dart
  nyxx_lavalink/lib/src/node/nodeRunner.dart
Labels: enhancement

#178 User accent color should be casted as an int.
  nyxx/lib/src/core/user/User.dart
Labels: bug

#159 Add sync control
  nyxx_interactions/lib/interactions.dart
  nyxx_interactions/lib/src/Interactions.dart
  nyxx_interactions/lib/src/builders/CommandPermissionBuilder.dart
  nyxx_interactions/lib/src/builders/SlashCommandBuilder.dart
  nyxx_interactions/lib/src/events/InteractionEvent.dart
  nyxx_interactions/lib/src/internal/sync/ICommandsSync.dart
  nyxx_interactions/lib/src/internal/sync/LockFileCommandSync.dart
  nyxx_interactions/lib/src/internal/sync/ManualCommandSync.dart
  nyxx_interactions/pubspec.yaml
Labels: enhancement

#173 Implement missing interaction features
  nyxx_interactions/lib/interactions.dart
  nyxx_interactions/lib/src/Interactions.dart
  nyxx_interactions/lib/src/events/InteractionEvent.dart
  nyxx_interactions/lib/src/internal/InteractionEndpoints.dart
  nyxx_interactions/lib/src/models/SlashCommand.dart
Labels: bug, enhancement

#188 [feature] Interaction improvements && fixes
  nyxx_interactions/lib/src/Interactions.dart
  nyxx_interactions/lib/src/events/InteractionEvent.dart
  nyxx_interactions/lib/src/internal/utils.dart
  nyxx_interactions/lib/src/models/Interaction.dart
Labels: bug, enhancement

#189 [feature/bug] Implement/Fix events in ShardManager
  nyxx/lib/src/internal/_ConnectionManager.dart
  nyxx/lib/src/internal/shard/Shard.dart
  nyxx/lib/src/internal/shard/ShardManager.dart
Labels: bug, enhancement
