Repository nyxx-discord/nyxx, pull requests merged in 2021-12, with the labels that each got.

#248 [feature] Guild events
  README.md
  lib/nyxx.dart
  lib/src/client_options.dart
  lib/src/core/guild/guild.dart
  lib/src/core/guild/scheduled_event.dart
  lib/src/events/guild_events.dart
  lib/src/internal/event_controller.dart
  lib/src/internal/http_endpoints.dart
  lib/src/internal/shard/shard.dart
  lib/src/utils/builders/guild_event_builder.dart
  test/integration/integration.dart
Labels: enhancement

#253 Don't propagate ready event early for NyxxWebsocket
  lib/src/nyxx.dart
Labels: bug

#256 Fix CliItegration plugin not working with IgnoreExceptions
  lib/src/plugin/plugins/ignore_exception.dart
Labels: bug

#259 Use logger instead of print
  lib/src/internal/shard/shard.dart
Labels: bug

#260 Fix typo in file name
  lib/nyxx.dart
  lib/src/plugin/plugin_manager.dart
Labels: bug

#261 bug: Nullable close code
  lib/src/internal/shard/shard.dart
Labels: bug

#262 bug: Missing ActivityBuilder
  lib/nyxx.dart
Labels: bug

#263 Release 3.0.1
  CHANGELOG.md
  lib/nyxx.dart
  lib/src/internal/constants.dart
  lib/src/internal/shard/shard.dart
  lib/src/plugin/plugin_manager.dart
  lib/src/plugin/plugins/ignore_exception.dart
  pubspec.yaml
Labels: bug

#266 Feature/specific shards
  .gitignore
  lib/src/client_options.dart
  lib/src/core/guild/guild.dart
  lib/src/internal/connection_manager.dart
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_manager.dart
Labels: enhancement

#268 feature/boost-progress-bar - implementation
  lib/src/core/guild/guild.dart
Labels: enhancement

#267 [feature] timeouts - implementation
  lib/nyxx.dart
  lib/src/core/user/member.dart
  lib/src/internal/http_endpoints.dart
  lib/src/plugin/plugins/ignore_exception.dart
  lib/src/utils/builders/member_builder.dart
  test/unit/builders_test.dart
Labels: enhancement

#270 Correctly initialise onDmReceived and onSelfMention
  lib/src/internal/event_controller.dart
  lib/src/nyxx.dart
Labels: bug

#271 Release 3.1.0
  .gitignore
  CHANGELOG.md
  lib/nyxx.dart
  lib/src/client_options.dart
  lib/src/core/guild/guild.dart
  lib/src/core/user/member.dart
  lib/src/internal/connection_manager.dart
  lib/src/internal/constants.dart
  lib/src/internal/event_controller.dart
  lib/src/internal/http_endpoints.dart
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_manager.dart
  lib/src/nyxx.dart
  lib/src/plugin/plugins/ignore_exception.dart
  lib/src/utils/builders/member_builder.dart
  pubspec.yaml
  test/unit/builders_test.dart
Labels: enhancement

#272 Expose builder parameter in IMember
  lib/src/core/user/member.dart
Labels: bug

#273 Hotfix 3.1.1
  CHANGELOG.md
  lib/src/internal/constants.dart
  pubspec.yaml
Labels: bug

#276 Add missing `ActivityType` of 3
  lib/src/core/user/presence.dart
  lib/src/utils/builders/presence_builder.dart
Labels: enhancement

#279 Release 3.2.0
  CHANGELOG.md
  lib/src/core/channel/guild/voice_channel.dart
  lib/src/core/guild/guild.dart
  lib/src/core/user/presence.dart
  lib/src/events/presence_update_event.dart
  lib/src/utils/builders/presence_builder.dart
Labels: bug, enhancement
