Repository nyxx-discord/nyxx, pull requests merged in 2022-07, with the labels that each got.

#356 Add MessageBuilder.limitLength
  lib/src/utils/builders/message_builder.dart
  test/unit/builders_test.dart
Labels: enhancement

#358 Correct uninitialised fields in events
  lib/src/events/guild_events.dart
  lib/src/events/message_events.dart
  lib/src/events/presence_update_event.dart
  lib/src/events/thread_members_update_event.dart
Labels: bug

#359 Correctly export HTTP route builders
  lib/nyxx.dart
  lib/src/internal/http/http_route_param.dart
  lib/src/internal/http/http_route_part.dart
Labels: bug

#360 fix: everyone role
  lib/src/core/guild/guild.dart
  lib/src/core/guild/role.dart
Labels: bug

#357 Release 4.0.0
  CHANGELOG.md
  lib/src/internal/constants.dart
  pubspec.yaml
Labels: bug, enhancement, documentation
