Repository nyxx-discord/nyxx, pull requests merged in 2022-05, with the labels that each got.

#341 Remove thread archive duration
  lib/src/core/guild/guild_feature.dart
Labels: bug

#316 Implement Dynamic Bucket Rate Limits
  lib/src/internal/http/http_bucket.dart
  lib/src/internal/http/http_handler.dart
  lib/src/internal/http/http_request.dart
  lib/src/internal/http/http_route.dart
  lib/src/internal/http/http_route_param.dart
  lib/src/internal/http/http_route_part.dart
  lib/src/internal/http_endpoints.dart
Labels: bug, enhancement

#332 feature: Implement forum channels
  lib/nyxx.dart
  lib/src/core/channel/channel.dart
  lib/src/core/channel/guild/forum/forum_channel.dart
  lib/src/core/channel/guild/forum/forum_tag.dart
  lib/src/core/channel/guild/guild_channel.dart
  lib/src/core/channel/guild/text_guild_channel.dart
  lib/src/internal/http_endpoints.dart
  lib/src/utils/builders/forum_thread_builder.dart
  lib/src/utils/builders/thread_builder.dart
  test/unit/builders_test.dart
Labels: enhancement

#347 Implement graceful shutdown
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_handler.dart
  lib/src/internal/shard/shard_manager.dart
  lib/src/nyxx.dart
  lib/src/plugin/plugins/cli_integration.dart
  lib/src/plugin/plugins/ignore_exception.dart
  lib/src/plugin/plugins/logging.dart
Labels: enhancement

#346 Add missing emoji endpoints
  lib/src/core/message/message.dart
  lib/src/internal/http_endpoints.dart
Labels: enhancement
