Repository nyxx-discord/nyxx, pull requests merged in 2022-03, with the labels that each got.

#305 Patch emojis & new properties
  example/emojis.dart
  lib/nyxx.dart
  lib/src/client_options.dart
  lib/src/core/message/components/message_component.dart
  lib/src/core/message/guild_emoji.dart
  lib/src/core/message/message.dart
  lib/src/core/message/reaction.dart
  lib/src/events/message_events.dart
  lib/src/internal/cache/cache_policy.dart
  lib/src/internal/cache/cacheable.dart
  lib/src/internal/http_endpoints.dart
  lib/src/nyxx.dart
  lib/src/utils/builders/message_builder.dart
Labels: enhancement

#308 Fixes name and format never being initilized for PartialSticker
  lib/src/core/message/sticker.dart
Labels: bug

#311 Add previous state to *UpdateEvents
  lib/src/core/message/message.dart
  lib/src/events/channel_events.dart
  lib/src/events/guild_events.dart
  lib/src/events/message_events.dart
  lib/src/events/voice_state_update_event.dart
Labels: enhancement

#313 Allow editing messages to remove content
  lib/src/core/audit_logs/audit_log_entry.dart
  lib/src/core/embed/embed.dart
  lib/src/core/embed/embed_provider.dart
  lib/src/core/guild/guild.dart
  lib/src/core/guild/guild_preview.dart
  lib/src/core/user/member.dart
  lib/src/events/channel_events.dart
  lib/src/internal/http_endpoints.dart
  lib/src/utils/builders/embed_builder.dart
  lib/src/utils/builders/message_builder.dart
  test/integration/integration.dart
  test/unit/builders_test.dart
Labels: bug

#315 Fix member not being initialiased in IMessage
  lib/src/core/message/message.dart
Labels: bug

#307 Fix target id property and add guild audit logs options
  lib/nyxx.dart
  lib/src/core/audit_logs/audit_log_entry.dart
  lib/src/core/audit_logs/audit_log_options.dart
Labels: bug, enhancement, blocked
