Repository nyxx-discord/nyxx, pull requests merged in 2022-04, with the labels that each got.

#319 Correct signature of StageVoiceGuildChannel
  lib/src/core/channel/guild/voice_channel.dart
Labels: bug

#321 feature: Handle missing internet
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_handler.dart
Labels: bug, enhancement

#324 bug: Remove Error from IHttpResponseError
  lib/nyxx.dart
  lib/src/internal/connection_manager.dart
  lib/src/internal/http/http_handler.dart
  lib/src/internal/http/http_response.dart
  lib/src/internal/http_endpoints.dart
Labels: bug

#325 feature: Move to API v10
  lib/src/client_options.dart
  lib/src/core/application/app_team_user.dart
  lib/src/core/channel/guild/text_guild_channel.dart
  lib/src/core/guild/guild.dart
  lib/src/core/guild/scheduled_event.dart
  lib/src/core/message/attachment.dart
  lib/src/core/message/components/message_component.dart
  lib/src/core/user/member.dart
  lib/src/events/message_events.dart
  lib/src/internal/cache/cache.dart
  lib/src/internal/constants.dart
  lib/src/internal/http_endpoints.dart
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_manager.dart
  lib/src/nyxx.dart
  lib/src/utils/builders/message_builder.dart
  test/integration/integration.dart
  test/unit/builders_test.dart
  test/unit/channel_test.dart
  test/unit/nyxx_test.dart
  test/unit/snowflake_test.dart
Labels: enhancement

#318 Add `@bannerUrl()` method
  lib/src/core/user/user.dart
  lib/src/internal/http_endpoints.dart
Labels: enhancement

#326 feature: Implement paginated bans
  lib/src/core/guild/guild.dart
  lib/src/internal/http_endpoints.dart
Labels: enhancement

#328 bugfix: failed to edit guild members
  lib/src/internal/http_endpoints.dart
Labels: bug

#335 Hotfix: Allow members to be disconnected by IMember.edit()
  CHANGELOG.md
  lib/src/utils/builders/member_builder.dart
  pubspec.yaml
Labels: bug

#334 maintenance: Fixup failing CI on PR due to missing secrets
  .github/workflows/unit_tests.yml
Labels: bug

#333 Fix typo
  lib/src/events/guild_events.dart
Labels: documentation

#338 feature/bugfix: `IGuild` fixes/Improvements; also add `@createGuild` on `INyxxWebsocket`
  lib/nyxx.dart
  lib/src/core/guild/guild.dart
  lib/src/core/guild/guild_welcome_screen.dart
  lib/src/core/guild/system_channel_flags.dart
  lib/src/core/user/presence.dart
  lib/src/internal/http_endpoints.dart
  lib/src/nyxx.dart
  lib/src/utils/builders/channel_builder.dart
  lib/src/utils/builders/guild_builder.dart
Labels: enhancement
