Repository nyxx-discord/nyxx, pull requests merged in 2022-11, with the labels that each got.

#380 feat: Add support for new select menus components
  lib/nyxx.dart
  lib/src/core/message/components/message_component.dart
Labels: enhancement

#383 Don't use ZlibDecoder to deflate gateway messages
  CHANGELOG.md
  lib/src/internal/constants.dart
  lib/src/internal/shard/shard_handler.dart
  pubspec.yaml
Labels: bug

#385 Prefer using throw over returning Future.error
  lib/src/internal/http/http_handler.dart
  lib/src/internal/http_endpoints.dart
Labels: bug

#386 Fix null-assert error on shard disposal; don't reconnect shard after disposing
  lib/src/internal/shard/shard_handler.dart
Labels: bug

#384 Cache user when fetching
  lib/src/internal/http_endpoints.dart
Labels: bug

#387 feature: missing forum channel features
  Makefile
  lib/nyxx.dart
  lib/src/core/channel/guild/forum/forum_channel.dart
  lib/src/core/channel/guild/forum/forum_channel_tags.dart
  lib/src/core/channel/guild/forum/forum_tag.dart
  lib/src/core/channel/thread_channel.dart
  lib/src/utils/builders/forum_thread_builder.dart
  lib/src/utils/builders/thread_builder.dart
  test/unit/application_test.dart
  test/unit/builders_test.dart
  test/unit/nyxx_test.dart
Labels: enhancement

#388 Add `activeDeveloper` flag
  lib/src/core/user/user_flags.dart
Labels: enhancement

#389 fix: add message content to client in examples
  example/channel.dart
  example/create_add_role.dart
  example/embeds.dart
  example/emojis.dart
  example/example.dart
  example/invite.dart
  example/kick_ban.dart
  example/permissions.dart
  example/ping_pong.dart
  example/reply_to_message.dart
  example/sending_file.dart
Labels: enhancement, documentation

#392 Emit bot start to plugins only when ready
  lib/src/nyxx.dart
Labels: bug

#395 Add retry with backoff to network operations (gateway and http)
  lib/src/client_options.dart
  lib/src/internal/exceptions/http_client_exception.dart
  lib/src/internal/http/http_handler.dart
  lib/src/internal/shard/message.dart
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_handler.dart
  pubspec.yaml
Labels: enhancement

#397 feature: add support for interaction webhooks
  lib/src/core/guild/webhook.dart
  lib/src/core/user/user.dart
  lib/src/internal/interfaces/message_author.dart
Labels: enhancement

#398 bug: Error when getting IInviteWithMeta from IGuildChannel
  lib/src/internal/http_endpoints.dart
Labels: bug

#400 hotfix: components parsing
  CHANGELOG.md
  lib/src/core/message/components/message_component.dart
  lib/src/internal/constants.dart
  pubspec.yaml
Labels: bug

#396 Add named arguments anywhere we can
  lib/src/core/guild/auto_moderation.dart
  lib/src/core/permissions/permissions.dart
  lib/src/core/permissions/permissions_constants.dart
  lib/src/utils/builders/auto_moderation_builder.dart
  lib/src/utils/builders/channel_builder.dart
  lib/src/utils/builders/embed_author_builder.dart
  lib/src/utils/builders/embed_builder.dart
  lib/src/utils/builders/embed_field_builder.dart
  lib/src/utils/builders/embed_footer_builder.dart
  lib/src/utils/builders/forum_thread_builder.dart
  lib/src/utils/builders/guild_builder.dart
  lib/src/utils/builders/guild_event_builder.dart
  lib/src/utils/builders/member_builder.dart
  lib/src/utils/builders/message_builder.dart
  lib/src/utils/builders/permissions_builder.dart
  lib/src/utils/builders/sticker_builder.dart
  lib/src/utils/builders/thread_builder.dart
  test/unit/builders_test.dart
Labels: enhancement

#402 Forward RetryOptions
  lib/nyxx.dart
Labels: enhancement

#403 Improve error handling and logging
  CONTRIBUTING.md
  lib/nyxx.dart
  lib/src/internal/connection_manager.dart
  lib/src/internal/http/http_bucket.dart
  lib/src/internal/http/http_handler.dart
  lib/src/internal/http/http_request.dart
  lib/src/internal/http/http_response.dart
  lib/src/internal/response_wrapper/error_response_wrapper.dart
  lib/src/internal/shard/shard.dart
  lib/src/nyxx.dart
  lib/src/plugin/plugin.dart
  lib/src/plugin/plugins/cli_integration.dart
  lib/src/plugin/plugins/ignore_exception.dart
  lib/src/plugin/plugins/logging.dart
Labels: enhancement

#409 Fix exports and GuildEventBuilder
  lib/nyxx.dart
  lib/src/utils/builders/guild_event_builder.dart
Labels: bug
