Repository nyxx-discord/nyxx, pull requests merged in 2023-01, with the labels that each got.

#420 feature: ETF Encoding
  lib/nyxx.dart
  lib/src/client_options.dart
  lib/src/core/audit_logs/audit_log_options.dart
  lib/src/core/message/attachment.dart
  lib/src/core/permissions/permission_overrides.dart
  lib/src/events/guild_events.dart
  lib/src/internal/constants.dart
  lib/src/internal/shard/message.dart
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_handler.dart
  pubspec.yaml
Labels: enhancement

#421 feature: ETF encoding stability and payload compression
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_handler.dart
  pubspec.yaml
Labels: bug, enhancement

#431 feature: New message types
  lib/src/core/message/message_type.dart
Labels: enhancement

#432 feature: Thread members details
  lib/nyxx.dart
  lib/src/client_options.dart
  lib/src/core/channel/thread_channel.dart
  lib/src/internal/http/http_route.dart
  lib/src/internal/http_endpoints.dart
  lib/src/utils/builders/guild_event_builder.dart
Labels: enhancement

#434 feature: Implement guild active threads endpoint
  lib/src/core/guild/guild.dart
  lib/src/internal/http_endpoints.dart
Labels: enhancement

#435 hotfix: Fix ratelimit handling
  CHANGELOG.md
  lib/src/internal/constants.dart
  lib/src/internal/http/http_handler.dart
  pubspec.yaml
Labels: bug

#436 feature: Audit log create event
  lib/src/events/guild_events.dart
  lib/src/internal/event_controller.dart
  lib/src/internal/http/http_handler.dart
  lib/src/internal/shard/shard.dart
Labels: enhancement
