Repository nyxx-discord/nyxx, pull requests merged in 2023-12, with the labels that each got.

#605 Add test validating ApiOptions.nyxxVersion
  test/unit/version_matches_test.dart
Labels: enhancement

#604 Export Credentials from package:oauth2
  lib/nyxx.dart
Labels: bug

#603 Provide guild ID when parsing message interactions
  lib/src/http/managers/message_manager.dart
Labels: bug

#599 Add entitlement delete payload
  lib/src/gateway/gateway.dart
  lib/src/models/gateway/events/entitlement.dart
  lib/src/utils/cache_helpers.dart
Labels: bug

#602 Add SKU flags field
  lib/nyxx.dart
  lib/src/http/managers/application_manager.dart
  lib/src/models/sku.dart
Labels: enhancement

#601 Add select menu default values
  lib/nyxx.dart
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/component.dart
Labels: enhancement

#607 Enable dartdoc link to source
  dartdoc_options.yaml
  lib/src/client_options.dart
  lib/src/http/route.dart
  lib/src/models/gateway/event.dart
  lib/src/models/guild/onboarding.dart
  lib/src/models/message/component.dart
Labels: documentation

#608 Release 6.1.0
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: bug, enhancement, documentation

#606 Remove nyxx_pagination from README
  README.md
Labels: documentation

#609 Release 6.1.0
  CHANGELOG.md
  README.md
  dartdoc_options.yaml
  lib/nyxx.dart
  lib/src/api_options.dart
  lib/src/builders/channel/group_dm.dart
  lib/src/builders/guild/guild.dart
  lib/src/builders/message/component.dart
  lib/src/builders/permission_overwrite.dart
  lib/src/client_options.dart
  lib/src/gateway/gateway.dart
  lib/src/http/managers/application_manager.dart
  lib/src/http/managers/channel_manager.dart
  lib/src/http/managers/guild_manager.dart
  lib/src/http/managers/message_manager.dart
  lib/src/http/managers/webhook_manager.dart
  lib/src/http/route.dart
  lib/src/models/gateway/event.dart
  lib/src/models/gateway/events/entitlement.dart
  lib/src/models/guild/onboarding.dart
  lib/src/models/message/component.dart
  lib/src/models/message/message.dart
  lib/src/models/sku.dart
  lib/src/utils/cache_helpers.dart
  pubspec.yaml
  test/unit/builders/permission_overwrite_test.dart
  test/unit/version_matches_test.dart
Labels: bug, enhancement, documentation

#611 Implement `username`/`avatarUrl` params for `WebhookManager#execute`
  lib/src/http/managers/webhook_manager.dart
  lib/src/models/webhook.dart
Labels: enhancement

#612 Prevent events from being dropped during the connection process
  lib/nyxx.dart
  lib/src/gateway/gateway.dart
  lib/src/gateway/message.dart
  lib/src/gateway/shard.dart
  lib/src/gateway/shard_runner.dart
  test/integration/gateway_integration_test.dart
Labels: bug

#613 Handle missing command permissions error
  lib/src/http/managers/application_command_manager.dart
  test/integration/rest_integration_test.dart
Labels: bug
