Repository nyxx-discord/nyxx, pull requests merged in 2023-03, with the labels that each got.

#429 Add missing thread features.
  example/private_emoji.dart
  lib/nyxx.dart
  lib/src/events/thread_create_event.dart
  lib/src/events/thread_list_sync_event.dart
  lib/src/events/thread_members_update_event.dart
  lib/src/internal/event_controller.dart
  lib/src/internal/shard/shard.dart
  lib/src/utils/builders/forum_thread_builder.dart
  test/unit/builders_test.dart
Labels: bug, enhancement

#448 documentation: Channel invites
  lib/src/core/channel/guild/guild_channel.dart
Labels: documentation

#451 Correctly dispose all resources on bot stop
  lib/src/internal/http/http_handler.dart
  lib/src/internal/shard/shard.dart
  lib/src/internal/shard/shard_handler.dart
  lib/src/nyxx.dart
Labels: bug
