Repository nyxx-discord/nyxx, pull requests merged in 2023-07, with the labels that each got.

#499 rewrite: Implement Stickers
  lib/nyxx.dart
  lib/src/builders/emoji/emoji.dart
  lib/src/builders/guild/guild.dart
  lib/src/builders/guild/scheduled_event.dart
  lib/src/builders/image.dart
  lib/src/builders/role.dart
  lib/src/builders/sticker.dart
  lib/src/builders/user.dart
  lib/src/builders/webhook.dart
  lib/src/client_options.dart
  lib/src/gateway/gateway.dart
  lib/src/http/handler.dart
  lib/src/http/managers/guild_manager.dart
  lib/src/http/managers/message_manager.dart
  lib/src/http/managers/sticker_manager.dart
  lib/src/http/request.dart
  lib/src/http/route.dart
  lib/src/manager_mixin.dart
  lib/src/models/gateway/events/guild.dart
  lib/src/models/guild/guild.dart
  lib/src/models/guild/guild_preview.dart
  lib/src/models/message/message.dart
  lib/src/models/sticker/global_sticker.dart
  lib/src/models/sticker/guild_sticker.dart
  lib/src/models/sticker/sticker.dart
  lib/src/models/sticker/sticker_pack.dart
  test/unit/builders/image_test.dart
  test/unit/http/managers/message_manager_test.dart
  test/unit/http/managers/sticker_manager_test.dart
Labels: rewrite

#506 Release 6.0.0-dev.1
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: rewrite

#507 Handle batch rate limits correctly
  lib/src/client.dart
  lib/src/http/bucket.dart
  lib/src/http/handler.dart
  test/unit/http/handler_test.dart
Labels: bug, rewrite

#508 Rewrite cdn
  lib/src/api_options.dart
  lib/src/http/cdn/cdn_asset.dart
  lib/src/http/cdn/cdn_request.dart
  lib/src/http/route.dart
  lib/src/models/application.dart
  lib/src/models/emoji.dart
  lib/src/models/guild/guild.dart
  lib/src/models/guild/member.dart
  lib/src/models/guild/scheduled_event.dart
  lib/src/models/message/author.dart
  lib/src/models/role.dart
  lib/src/models/team.dart
  lib/src/models/user/user.dart
  lib/src/models/webhook.dart
  test/integration/rest_integration_test.dart
Labels: enhancement, rewrite

#509 fix: throwing error on null description
  lib/src/http/managers/sticker_manager.dart
  lib/src/models/sticker/global_sticker.dart
  lib/src/models/sticker/guild_sticker.dart
Labels: rewrite

#511 Improve CDN rewrite
  lib/nyxx.dart
  lib/src/http/cdn/cdn_asset.dart
  lib/src/http/cdn/cdn_request.dart
  lib/src/http/handler.dart
Labels: enhancement, rewrite
