Repository nyxx-discord/nyxx, pull requests merged in 2023-11, with the labels that each got.

#580 Improve caching and reduce incorrect ID use
  lib/src/cache/cache.dart
  lib/src/gateway/gateway.dart
  lib/src/http/managers/application_command_manager.dart
  lib/src/http/managers/audit_log_manager.dart
  lib/src/http/managers/auto_moderation_manager.dart
  lib/src/http/managers/channel_manager.dart
  lib/src/http/managers/emoji_manager.dart
  lib/src/http/managers/entitlement_manager.dart
  lib/src/http/managers/guild_manager.dart
  lib/src/http/managers/integration_manager.dart
  lib/src/http/managers/interaction_manager.dart
  lib/src/http/managers/invite_manager.dart
  lib/src/http/managers/member_manager.dart
  lib/src/http/managers/message_manager.dart
  lib/src/http/managers/role_manager.dart
  lib/src/http/managers/scheduled_event_manager.dart
  lib/src/http/managers/sticker_manager.dart
  lib/src/http/managers/user_manager.dart
  lib/src/http/managers/voice_manager.dart
  lib/src/http/managers/webhook_manager.dart
  lib/src/models/gateway/events/channel.dart
  lib/src/models/interaction.dart
  lib/src/models/message/message.dart
  lib/src/models/voice/voice_state.dart
  lib/src/utils/cache_helpers.dart
  test/mocks/client.dart
  test/unit/http/managers/member_manager_test.dart
  test/unit/http/managers/scheduled_event_manager_test.dart
  test/unit/http/managers/user_manager_test.dart
  test/unit/http/managers/voice_manager_test.dart
Labels: bug, enhancement

#581 Release 6.0.1
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: bug, enhancement

#585 Fix autocompletion interaction responses
  lib/src/builders/interaction_response.dart
Labels: bug

#584 Correct assertions in Interaction.respond
  lib/src/models/interaction.dart
Labels: bug

#588 Release 6.0.2
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: bug

#590 add permission splits
  lib/src/models/permissions.dart
Labels: enhancement

#591 Correctly build autocompletion responses
  lib/src/builders/interaction_response.dart
  test/unit/builders/interaction_response_test.dart
Labels: bug

#593 Release 6.0.3
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: bug
