Repository nyxx-discord/nyxx, pull requests merged in 2023-09, with the labels that each got.

#530 Fix parsing members received in interaction resolved_data
  lib/src/http/managers/interaction_manager.dart
  lib/src/http/managers/member_manager.dart
  test/unit/http/managers/interaction_manager_test.dart
Labels: bug

#532 Add onRateLimit stream to HttpHandler
  lib/nyxx.dart
  lib/src/http/handler.dart
  test/unit/http/handler_test.dart
Labels: enhancement

#533 Use more precise emoji type in reaction events
  lib/src/models/gateway/events/message.dart
Labels: enhancement

#545 Improve plugin interface
  lib/src/client.dart
  lib/src/plugin/cli_integration.dart
  lib/src/plugin/ignore_exceptions.dart
  lib/src/plugin/logging.dart
  lib/src/plugin/plugin.dart
Labels: enhancement

#546 Make filename required in AttachmentBuilder
  lib/src/builders/message/attachment.dart
Labels: bug

#550 Fix assertion in DiscordColor
  lib/src/models/discord_color.dart
  test/unit/models/discord_color_test.dart
Labels: bug

#549 Allow users to specify stdout and stderr in Logging plugin
  README.md
  lib/src/plugin/logging.dart
Labels: enhancement

#551 Add caching of current user
  lib/src/client.dart
  lib/src/client_options.dart
  test/integration/rest_integration_test.dart
Labels: enhancement

#552 Bug/parse role mentions
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/message.dart
  pubspec.yaml
Labels: bug

#547 Make attachment implement CdnAsset
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/attachment.dart
  test/integration/rest_integration_test.dart
Labels: enhancement

#535 Various message component bug fixes
  lib/src/builders/interaction_response.dart
  lib/src/builders/message/component.dart
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/component.dart
Labels: bug

#556 chore: add missing state field in ActivityBuilder
  lib/src/builders/presence.dart
Labels: enhancement

#559 Remove string casts for `Snowflake.parse`
  lib/src/gateway/gateway.dart
  lib/src/http/managers/audit_log_manager.dart
  lib/src/http/managers/emoji_manager.dart
  lib/src/http/managers/guild_manager.dart
  lib/src/http/managers/invite_manager.dart
  lib/src/http/managers/message_manager.dart
  lib/src/http/managers/sticker_manager.dart
  lib/src/http/managers/user_manager.dart
  lib/src/http/managers/voice_manager.dart
Labels: bug

#560 CONTRIBUTING: Add conventions about branches
  CONTRIBUTING.md
Labels: documentation

#561 fix: invalid client voice state update, export NyxxPluginState
  lib/nyxx.dart
  lib/src/builders/voice.dart
Labels: bug
