Repository nyxx-discord/nyxx, pull requests merged in 2023-10, with the labels that each got.

#564 Update mentions field in message update event to be nullable
  lib/src/gateway/gateway.dart
  lib/src/models/gateway/events/message.dart
Labels: bug

#565 Improve plugin interface and errors
  lib/nyxx.dart
  lib/src/client.dart
  lib/src/errors.dart
  lib/src/models/channel/thread.dart
  lib/src/plugin/plugin.dart
Labels: enhancement

#566 Prepare to Release 6.0.0
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: bug, enhancement

#571 fix: incorrect "description_localizations" key's value build in CommandOptionBuilder
  lib/src/builders/application_command.dart
  lib/src/http/managers/channel_manager.dart
  lib/src/plugin/ignore_exceptions.dart
Labels: bug

#575 Fix voice states not being cached correctly in GUILD_CREATE event
  lib/src/gateway/gateway.dart
  lib/src/http/managers/voice_manager.dart
  lib/src/models/guild/guild.dart
  lib/src/models/voice/voice_state.dart
Labels: bug

#576 Fix parsing scheduled events without channels
  lib/src/http/managers/scheduled_event_manager.dart
  test/unit/http/managers/scheduled_event_manager_test.dart
Labels: bug

#577 Fix using ephemeral responses with message component interactions
  lib/src/models/interaction.dart
Labels: bug

#578 Fix parsing message component label when it is null
  lib/src/http/managers/message_manager.dart
Labels: bug
