Repository nyxx-discord/nyxx, pull requests merged in 2023-08, with the labels that each got.

#514 Fix typo: chanel -> channel
  lib/src/http/managers/channel_manager.dart
  lib/src/models/channel/thread.dart
  lib/src/models/channel/voice_channel.dart
Labels: documentation

#510 Add more bitwise operators on `Flags`
  lib/src/utils/flags.dart
Labels: enhancement, rewrite

#512 Rewrite interactions
  example/application_commands.dart
  example/message_components.dart
  lib/nyxx.dart
  lib/src/builders/application_command.dart
  lib/src/builders/interaction_response.dart
  lib/src/builders/message/component.dart
  lib/src/builders/message/message.dart
  lib/src/builders/sentinels.dart
  lib/src/cache/cache.dart
  lib/src/client.dart
  lib/src/client_options.dart
  lib/src/event_mixin.dart
  lib/src/gateway/gateway.dart
  lib/src/http/handler.dart
  lib/src/http/managers/application_command_manager.dart
  lib/src/http/managers/application_manager.dart
  lib/src/http/managers/audit_log_manager.dart
  lib/src/http/managers/auto_moderation_manager.dart
  lib/src/http/managers/emoji_manager.dart
  lib/src/http/managers/guild_manager.dart
  lib/src/http/managers/integration_manager.dart
  lib/src/http/managers/interaction_manager.dart
  lib/src/http/managers/member_manager.dart
  lib/src/http/managers/message_manager.dart
  lib/src/http/managers/role_manager.dart
  lib/src/http/managers/scheduled_event_manager.dart
  lib/src/http/managers/sticker_manager.dart
  lib/src/http/managers/webhook_manager.dart
  lib/src/http/route.dart
  lib/src/manager_mixin.dart
  lib/src/models/commands/application_command.dart
  lib/src/models/commands/application_command_option.dart
  lib/src/models/commands/application_command_permissions.dart
  lib/src/models/gateway/events/application_command.dart
  lib/src/models/gateway/events/interaction.dart
  lib/src/models/guild/guild.dart
  lib/src/models/guild/member.dart
  lib/src/models/interaction.dart
  lib/src/models/message/component.dart
  lib/src/models/message/message.dart
  test/integration/rest_integration_test.dart
  test/unit/http/managers/application_command_manager_test.dart
  test/unit/http/managers/application_manager_test.dart
  test/unit/http/managers/interaction_manager_test.dart
Labels: rewrite

#518 Improve cache clearing
  lib/src/cache/cache.dart
Labels: bug, enhancement

#517 Add latency tracking features to rewrite
  lib/src/gateway/event_parser.dart
  lib/src/gateway/gateway.dart
  lib/src/gateway/shard.dart
  lib/src/gateway/shard_runner.dart
  lib/src/http/handler.dart
  lib/src/models/gateway/event.dart
  test/integration/gateway_integration_test.dart
  test/integration/rest_integration_test.dart
Labels: enhancement, rewrite

#520 Don't stringify classes without ToStringHelper
  lib/src/utils/to_string_helper/mirrors_impl.dart
Labels: bug, rewrite

#522 Add allPermissions getter
  lib/src/models/permissions.dart
Labels: enhancement, rewrite

#521 Fix message update parsing
  lib/src/gateway/gateway.dart
Labels: bug

#519 Clean up interaction response code
  lib/src/builders/interaction_response.dart
  lib/src/builders/message/message.dart
  lib/src/models/interaction.dart
Labels: rewrite

#523 Add back a way for users to create ephemeral interaction followups
  lib/src/http/managers/interaction_manager.dart
  lib/src/models/interaction.dart
Labels: bug

#524 Make all builders mutable
  lib/src/builders/application_command.dart
  lib/src/builders/application_role_connection.dart
  lib/src/builders/channel/channel_position.dart
  lib/src/builders/channel/forum_tag.dart
  lib/src/builders/channel/group_dm.dart
  lib/src/builders/channel/guild_channel.dart
  lib/src/builders/channel/stage_instance.dart
  lib/src/builders/channel/thread.dart
  lib/src/builders/emoji/emoji.dart
  lib/src/builders/emoji/reaction.dart
  lib/src/builders/guild/auto_moderation.dart
  lib/src/builders/guild/guild.dart
  lib/src/builders/guild/member.dart
  lib/src/builders/guild/scheduled_event.dart
  lib/src/builders/guild/template.dart
  lib/src/builders/guild/welcome_screen.dart
  lib/src/builders/guild/widget.dart
  lib/src/builders/image.dart
  lib/src/builders/interaction_response.dart
  lib/src/builders/invite.dart
  lib/src/builders/message/allowed_mentions.dart
  lib/src/builders/message/attachment.dart
  lib/src/builders/message/component.dart
  lib/src/builders/message/message.dart
  lib/src/builders/permission_overwrite.dart
  lib/src/builders/presence.dart
  lib/src/builders/role.dart
  lib/src/builders/sticker.dart
  lib/src/builders/user.dart
  lib/src/builders/voice.dart
  lib/src/builders/webhook.dart
Labels: enhancement

#525 Add EmbedBuilder
  lib/nyxx.dart
  lib/src/builders/message/embed.dart
  lib/src/builders/message/message.dart
  test/unit/builders/message/message_test.dart
Labels: enhancement, rewrite

#526 Release 6.0.0-dev.2
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: rewrite

#528 Fix sending text emoji in SelectMenuOptionBuilder
  lib/src/builders/message/component.dart
  test/integration/rest_integration_test.dart
Labels: bug

#527 Add CommandOptionMentionable type
  lib/nyxx.dart
  lib/src/models/commands/application_command_option.dart
  lib/src/models/role.dart
  lib/src/models/user/user.dart
Labels: enhancement

#529 Add errors to handle interaction responses
  lib/nyxx.dart
  lib/src/errors.dart
  lib/src/models/interaction.dart
Labels: rewrite

#531 Add helper constructors to some builders
  lib/src/builders/channel/thread.dart
  lib/src/builders/message/component.dart
  lib/src/builders/sticker.dart
Labels: enhancement
