Repository nyxx-discord/nyxx, pull requests merged in 2024-01, with the labels that each got.

#614 Rate limit outgoing gateway events
  lib/src/gateway/event_parser.dart
  lib/src/gateway/gateway.dart
  lib/src/gateway/shard.dart
  lib/src/gateway/shard_runner.dart
  test/integration/gateway_integration_test.dart
Labels: bug

#617 Widen type of RoleUpdateBuilder.permissions
  lib/src/builders/role.dart
Labels: bug

#616 Export unexported types
  lib/nyxx.dart
Labels: bug

#615 Allow plugins to intercept HTTP requests and Gateway events
  lib/src/client.dart
  lib/src/gateway/shard.dart
  lib/src/http/handler.dart
  lib/src/plugin/plugin.dart
  test/integration/gateway_integration_test.dart
Labels: enhancement

#618 Correct serialization of request body in MessageManager.bulkDelete
  lib/src/http/managers/message_manager.dart
  test/integration/rest_integration_test.dart
Labels: bug

#619 Parse GuildDeleteEvent.isUnavailable even when unavailable is not present
  lib/src/gateway/gateway.dart
Labels: bug

#620 Correct getting started link in README
  README.md
Labels: documentation

#621 Correct serialization of guild builders
  lib/src/builders/guild/guild.dart
Labels: bug

#625 Fix parsing role flags in guild templates
  lib/src/http/managers/guild_manager.dart
Labels: bug

#627 Fixed hoist attribute in both role builder and role update builder
  lib/src/builders/role.dart
Labels: bug
