Repository nyxx-discord/nyxx, pull requests merged in 2024-10, with the labels that each got.

#698 Don't modify Cache.keys during iteration
  lib/src/cache/cache.dart
  test/unit/cache/cache_test.dart
Labels: bug

#703 Add missing subscription manager getter
  lib/src/client_options.dart
  lib/src/http/managers/subscription_manager.dart
  lib/src/models/sku.dart
Labels: bug

#704 Set limits on the default maximum cache sizes
  lib/src/client_options.dart
Labels: bug

#709 Handle missing mention_roles field
  lib/src/http/managers/message_manager.dart
  test/integration/rest_integration_test.dart
  test/unit/http/managers/message_manager_test.dart
Labels: bug

#710 Release 6.4.3
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: bug

#715 add new member flags
  lib/src/models/guild/member.dart
Labels: enhancement

#716 add new fields on message snapshot
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/message.dart
Labels: enhancement

#717 fix serialisation of `before` param in `listJoinedPrivateArchivedThreads`
  lib/src/http/managers/channel_manager.dart
Labels: bug

#720 Recurrence rule can be set to null when updating
  lib/src/builders/guild/scheduled_event.dart
  lib/src/builders/sentinels.dart
Labels: enhancement

#708 add support for soundboard
  lib/src/builders/channel/forum_tag.dart
  lib/src/builders/channel/guild_channel.dart
  lib/src/builders/guild/welcome_screen.dart
  lib/src/builders/image.dart
  lib/src/builders/sentinels.dart
  lib/src/builders/sound.dart
  lib/src/builders/soundboard.dart
  lib/src/client_options.dart
  lib/src/errors.dart
  lib/src/event_mixin.dart
  lib/src/gateway/gateway.dart
  lib/src/http/managers/soundboard_manager.dart
  lib/src/http/route.dart
  lib/src/manager_mixin.dart
  lib/src/models/gateway/events/soundboard.dart
  lib/src/models/gateway/events/voice.dart
  lib/src/models/guild/guild.dart
  lib/src/models/soundboard/soundboard.dart
  lib/src/utils/building_helpers.dart
  lib/src/utils/cache_helpers.dart
  test/files/sound.ogg
  test/integration/rest_integration_test.dart
  test/unit/builders/sound_test.dart
  test/unit/http/managers/soundboard_manager_test.dart
Labels: enhancement

#719 Allow polls to be constructed in a interation response
  lib/src/builders/message/message.dart
Labels: enhancement

#676 add banner property to member
  lib/src/http/cdn/cdn_request.dart
  lib/src/http/managers/member_manager.dart
  lib/src/models/guild/member.dart
  test/unit/http/bucket_test.dart
  test/unit/http/cdn_test.dart
  test/unit/http/managers/member_manager_test.dart
Labels: enhancement

#718 fix user avatar decoration, add member avatar decoration
  lib/src/http/managers/member_manager.dart
  lib/src/http/managers/user_manager.dart
  lib/src/http/route.dart
  lib/src/models/guild/member.dart
  lib/src/models/user/avatar_decoration_data.dart
  lib/src/models/user/user.dart
Labels: bug, enhancement
