Repository nyxx-discord/nyxx, pull requests merged in 2024-06, with the labels that each got.

#662 fix automod: Add missing types
  lib/src/models/guild/auto_moderation.dart
Labels: bug

#663 fix: update auto-mod builders
  lib/src/builders/guild/auto_moderation.dart
Labels: enhancement

#664 Add blockMemberInteraction action type
  lib/src/models/guild/auto_moderation.dart
Labels: enhancement

#660 Add `ButtonStyle.premium` and deprecate `InteractionCallbackType.premiumRequired`
  lib/src/builders/interaction_response.dart
  lib/src/builders/message/component.dart
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/component.dart
Labels: enhancement

#665 Replace (almost) all parsable enums to an enum-like class
  lib/src/gateway/gateway.dart
  lib/src/http/managers/application_command_manager.dart
  lib/src/http/managers/application_manager.dart
  lib/src/http/managers/audit_log_manager.dart
  lib/src/http/managers/auto_moderation_manager.dart
  lib/src/http/managers/channel_manager.dart
  lib/src/http/managers/entitlement_manager.dart
  lib/src/http/managers/gateway_manager.dart
  lib/src/http/managers/guild_manager.dart
  lib/src/http/managers/integration_manager.dart
  lib/src/http/managers/interaction_manager.dart
  lib/src/http/managers/invite_manager.dart
  lib/src/http/managers/message_manager.dart
  lib/src/http/managers/scheduled_event_manager.dart
  lib/src/http/managers/sticker_manager.dart
  lib/src/http/managers/user_manager.dart
  lib/src/http/managers/webhook_manager.dart
  lib/src/models/application.dart
  lib/src/models/channel/channel.dart
  lib/src/models/channel/stage_instance.dart
  lib/src/models/channel/types/forum.dart
  lib/src/models/channel/voice_channel.dart
  lib/src/models/commands/application_command.dart
  lib/src/models/commands/application_command_option.dart
  lib/src/models/commands/application_command_permissions.dart
  lib/src/models/entitlement.dart
  lib/src/models/guild/audit_log.dart
  lib/src/models/guild/auto_moderation.dart
  lib/src/models/guild/guild.dart
  lib/src/models/guild/integration.dart
  lib/src/models/guild/onboarding.dart
  lib/src/models/guild/scheduled_event.dart
  lib/src/models/interaction.dart
  lib/src/models/invite/invite.dart
  lib/src/models/locale.dart
  lib/src/models/message/activity.dart
  lib/src/models/message/component.dart
  lib/src/models/message/message.dart
  lib/src/models/message/poll.dart
  lib/src/models/permission_overwrite.dart
  lib/src/models/presence.dart
  lib/src/models/sku.dart
  lib/src/models/sticker/sticker.dart
  lib/src/models/team.dart
  lib/src/models/user/connection.dart
  lib/src/models/user/user.dart
  lib/src/models/webhook.dart
  lib/src/utils/enum_like.dart
Labels: bug, enhancement
