Repository nyxx-discord/nyxx, pull requests merged in 2024-09, with the labels that each got.

#683 Add missing `approximateUserInstallCount` to `Application`
  lib/nyxx.dart
  lib/src/http/managers/application_manager.dart
  lib/src/models/application.dart
  test/unit/http/managers/application_manager_test.dart
Labels: enhancement

#684 Add missing audit log event types
  lib/src/models/guild/audit_log.dart
Labels: enhancement

#685 Add auditLogReason to followChannel
  lib/src/http/managers/channel_manager.dart
  lib/src/models/channel/channel.dart
Labels: enhancement

#686 Add recurrence rules for scheduled events
  lib/nyxx.dart
  lib/src/builders/guild/scheduled_event.dart
  lib/src/http/managers/scheduled_event_manager.dart
  lib/src/models/guild/scheduled_event.dart
  test/unit/http/managers/scheduled_event_manager_test.dart
Labels: bug, enhancement

#689 Add missing fields to Message
  lib/nyxx.dart
  lib/src/builders/message/message.dart
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/embed.dart
  lib/src/models/message/message.dart
  lib/src/models/message/reference.dart
  lib/src/models/message/role_subscription_data.dart
Labels: enhancement

#688 Add type field to Invite
  lib/nyxx.dart
  lib/src/http/managers/invite_manager.dart
  lib/src/models/invite/invite.dart
  lib/src/models/invite/invite_metadata.dart
  test/unit/http/managers/invite_manager_test.dart
Labels: enhancement

#693 Delete any commands left over in tests
  test/integration/rest_integration_test.dart
Labels: bug

#692 Add fetch voice state endpoints
  lib/src/http/managers/voice_manager.dart
  test/unit/http/managers/voice_manager_test.dart
Labels: enhancement

#690 Add support for subscriptions
  lib/nyxx.dart
  lib/src/client_options.dart
  lib/src/errors.dart
  lib/src/http/managers/application_manager.dart
  lib/src/http/managers/sku_manager.dart
  lib/src/http/managers/subscription_manager.dart
  lib/src/http/route.dart
  lib/src/models/application.dart
  lib/src/models/sku.dart
  lib/src/models/subscription.dart
  lib/src/utils/cache_helpers.dart
  test/integration/rest_integration_test.dart
  test/unit/http/managers/application_manager_test.dart
  test/unit/http/managers/sku_manager_test.dart
  test/unit/http/managers/subscription_manager_test.dart
Labels: enhancement

#687 Add update onboarding endpoint to GuildManager
  lib/nyxx.dart
  lib/src/builders/guild/onboarding.dart
  lib/src/http/managers/guild_manager.dart
  lib/src/models/guild/guild.dart
  lib/src/models/guild/onboarding.dart
  test/unit/http/managers/guild_manager_test.dart
Labels: enhancement

#678 Add application emojis
  lib/nyxx.dart
  lib/src/builders/emoji/emoji.dart
  lib/src/builders/sentinels.dart
  lib/src/http/managers/emoji_manager.dart
  lib/src/models/application.dart
  lib/src/models/emoji.dart
  lib/src/models/guild/guild.dart
  lib/src/utils/cache_helpers.dart
  test/unit/http/managers/emoji_manager_test.dart
Labels: enhancement

#694 Improve cache implementation
  example/simple_command.dart
  lib/nyxx.dart
  lib/src/builders/interaction_response.dart
  lib/src/cache/cache.dart
  lib/src/client.dart
  lib/src/http/managers/application_command_manager.dart
  lib/src/http/managers/channel_manager.dart
  lib/src/http/managers/manager.dart
  lib/src/http/managers/voice_manager.dart
  lib/src/models/guild/guild.dart
  test/mocks/client.dart
  test/unit/builders/message/message_test.dart
  test/unit/cache/cache_test.dart
  test/unit/http/managers/message_manager_test.dart
Labels: bug
