Repository nyxx-discord/nyxx, pull requests merged in 2024-07, with the labels that each got.

#668 fix: interaction metadata user is an object now
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/message.dart
  test/unit/http/managers/message_manager_test.dart
Labels: bug

#670 Release 6.3.0
  CHANGELOG.md
  lib/src/api_options.dart
  pubspec.yaml
Labels: bug, enhancement

#673 fix: `answer_id` being null
  lib/src/http/managers/message_manager.dart
  test/unit/http/managers/message_manager_test.dart
Labels: bug

#679 add new permissions
  lib/src/models/permissions.dart
Labels: enhancement
