Repository nyxx-discord/nyxx, pull requests merged in 2025-03, with the labels that each got.

#743 Handle abnormalClosure
  lib/src/gateway/shard_runner.dart
Labels: enhancement

#744 rename `guildEmojisAndStickers` intent to `guildExpressions`
  lib/src/intents.dart
Labels: documentation

#742 Implement components V2
  lib/nyxx.dart
  lib/src/builders/interaction_response.dart
  lib/src/builders/message/component.dart
  lib/src/builders/message/message.dart
  lib/src/http/managers/message_manager.dart
  lib/src/models/message/component.dart
  lib/src/models/message/message.dart
  lib/src/models/soundboard/soundboard.dart
  pubspec.yaml
  test/integration/async_dispose_test.dart
  test/integration/rest_integration_test.dart
  test/unit/builders/message/message_test.dart
  test/unit/http/managers/message_manager_test.dart
Labels: enhancement, minor change
